### ISSUE TITLE
Simple way of getting Tor using the Internet Archive's Wayback Machine

### ISSUE THREAD

**Issue by ghost** [TheTorProject/gettor#16]
One should first save the torproject.org main website using,

https://web.archive.org/save/https://www.torproject.org/

Then one should locate the URL of the download page, and save it using,

https://web.archive.org/save/https://www.torproject.org/download/download-easy.html.en

Then clicking on "Download" button should load the download process and FF says that the download's URL comes from archive.org, in other words one should block archive.org for this method to not work.

I tested it at my home by blocking torproject.org on my router, the download started nevertheless.

**Comment by Shifterovich** [comment]
```
Loading...

https://www.torproject.org/dist/torbrowser/6.0.8/tor-browser-linux64-6.0.8_en-US.tar.xz | 12:06:21 Led 2, 2017

Got an HTTP 302 response at crawl time

Redirecting to...

https://dist.torproject.org/torbrowser/6.0.8/tor-browser-linux64-6.0.8_en-US.tar.xz
```

**Comment by e5f3c2ea895af0f27667** [comment]
@Shifterovich Thanks for testing!

**Comment by mrphs** [comment]
@Shifterovich are you sure it's being downloaded from archive.org? When I tried it eventually redirected the request to dist.torproject.org

Another caveat of this method is that users might get an old and vulnerable version this way.

**Comment by Shifterovich** [comment]
@mrphs It just says that the URL redirects to dist.torproject.org/....., but archive.org still acts like a proxy between you and dist.torproject.org. I even tried blocking dist.torproject.org.

**Comment by ilv** [comment]
@e5f3c2ea895af0f27667 Thanks, this looks interesting. As I mentioned in tor-talk, you can actually generate a direct download link depending on the latest version. We could send those links via GetTor and update it every time there is a new version of Tor Browser released. Links to older versions won't work because archive.org will try to save an nonexistent file.

**Comment by e5f3c2ea895af0f27667** [comment]
Thanks @ilv

Ideally I think it would be better to launch a Tor Project archive account from which all other Tor versions are  uploaded and GetTor would send the latest version, this would mitigate any possible problems with the link Tor Site<->Wayback Machine<->User.

**Comment by ilv** [comment]
Moving tickets to trac: https://trac.torproject.org/projects/tor/ticket/22665
